### ISSUE TITLE
Sharing enemies, language and nbReplays

### ISSUE THREAD

**Issue by Illedan** [s-vivien/CGBenchmark#5]
Is it possible to share `enemies, language and nbReplays` between all codes or do we have to copy paste?
Would be nice with a shared option. To only set it once. (to not mess up the agentsIds and replay counts.)

Also:
Temporary results line could contain the filename for convenience when scrolling the terminal.

And:
Why is enemy crashes added to the crashes counter?
`18:11:23,168 INFO  [    Illedan ][   SEED 8 ] https://www.codingame.com/replay/429729375 1:ValNykol 2:[ME] 3:Marchete 4:Neumann (CRASH)`

Anyway, great tool 🚀

**Comment by s-vivien** [comment]
See latest push :D
Thanks for the suggestions !
